### ISSUE TITLE
场景测试——准备工作

### ISSUE THREAD

**Issue by YiWei0921** [LuonaticJiesus/Alpha_Document#25]
后台为我们添加几个账号（如果不方便添加就给现有账号移除，每个人再重新注册一个），并修改相关权限
以下为代称A——xsp，B——mtr，C——lc，D——zyl，E——zql，F——gym
新增模块——软件工程（课程）
A是软工的老师，B是超级管理员，C是助教，D,E分别是课程的学生，F是纯鹿人

**Comment by GreenDragon666** [comment]
1. 验证邮件所提供的链接不能自动跳转回原来的网站——修改为提供带参数的链接直接到前端，前端直接检查路由再向后端发请求
2. 注册界面邮箱匹配有错误，邮箱间隔的"."可以使任意字符
