### ISSUE TITLE
改进三

### ISSUE THREAD

**Issue by YiWei0921** [LuonaticJiesus/Alpha_Document#33]
![image](https://github.com/LuonaticJiesus/Alpha_Document/assets/109458903/1077e118-b012-4a0f-a5fa-878f02693ff1)

**Comment by Mashiroln** [comment]
这应该是Home界面嵌入的编辑器，调试时使用忘记删除了。如果有时间，麻烦联系开发（前后端均可）获得助教权限->进入模块->点击右侧通知版上方的”发布通知“，再进行测试。
目前根据开发者的测试，上述步骤打开的通知编辑器是可以关闭的。
